import type { Metadata } from "next";
import { NunitoSans } from "../font/NunitoSans";
import "./globals.css";
import Navbar from "./_layouts/Navbar";

export const metadata: Metadata = {
  title: "Next-TopUp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={NunitoSans.variable}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
